### ISSUE TITLE
Close Dropdown and collapsable nav bar

### ISSUE THREAD

**Issue by namtrik** [creativetimofficial/ct-vue-now-ui-kit-pro#6]
Hello, I would like to know from the "MainNavbar.vue" how I can do to close the dropdown from a nav-link on click  and also how to close the collapse nav bar from a nav item on click also. Thanks
<img width="637" alt="captura de pantalla 2018-12-10 a la s 7 19 48 p m" src="https://user-images.githubusercontent.com/44480034/49770100-ec145800-fcb0-11e8-8c5c-8c0c9ba19d54.png">

**Comment by cristijora** [comment]
Hello @namtrik 

We recently did an update to the template and would recommend getting the latest version.
As for your question you for the first part, you can do it like this
```html
<template slot="navbar-menu" slot-scope="{close}">
 <li class="nav-item" @click="close">
....
</template>
```

As for the second one, it's a bit more tricky but you can follow the same principle as the one done with `nav-link` and close navbar.
First add this code to `drop-down` component
```js
    provide() {
      return {
        closeDropDown: this.closeDropDown
      }
    }
```

Then go to `Nav-link` component and add `closeDropDown` to `inject` section
`inject: ['closeNavbar', 'closeDropDown']`. You might have `close` instead of `closeNavbar` in the older version.

Add this piece of code inside `NavLink.vue` inside `closeNav` method
```
 if (this.closeDropDown) {
       this.closeDropDown()
}
```

Now whenever you have a `nav-link` inside a `drop-down` it will automatically close the dropdown after navigating to the necessary page

PS: After writing this, realized that this might be a useful feature indeed and added it to the template and now it should be there if you re-download it.
